### ISSUE TITLE
import reactor.Environment;

### ISSUE THREAD

**Issue by farrouha** [mp911de/reactive-spring#1] opened 2018-03-13 12:50 UTC
import dependency does not work despite it exists in pom.xml 
![capture1](https://user-images.githubusercontent.com/25324315/37342637-7c3d4f12-26c5-11e8-88fb-1bb5ad060c3e.PNG)
![capture2](https://user-images.githubusercontent.com/25324315/37342657-83f37e66-26c5-11e8-8224-a0f4c6f2b879.PNG)

**Comment by esraalela** [comment] 2018-11-06 14:37
I had the same issue, it was fixed after I add these external JARs:

https://jar-download.com/artifacts/io.projectreactor/reactor-core/2.0.8.RELEASE/source-code

**Comment by mp911de** [comment] 2019-03-11 16:31
Closing as the issue is invalid. We're using Reactor 3.2 here, 2.0 is outdated since quite a while.

**Closed as completed by mp911de** 2019-03-11 16:31 UTC
Labels: invalid

**Comment by authentical** [comment] 2019-10-16 18:52
Hi there. I had the same problem as the original user. 

   <groupId>io.projectreactor</groupId>
    <artifactId>reactor-core</artifactId>
    <version>3.3.0.RELEASE</version>
Did not offer the Environment variable expected from reactor.

I followed the instruction from farrouha and found that  suddenly I had access to Environment .

Is Environment now missing from reactor core? Perhaps it's just an outdated way to do things but I didn't expect Environment  to disappear.
